<?php

namespace Database\Seeders;

use App\Models\Car;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CarSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        Car::insert([
            [
                'user_id' => 1,
                'brand_id' => 1, // Audi
                'fuel_id' => 1, // Essence
                'model' => 'A3',
                'etat' => 'occasion',
                'annee' => 2020,
                'kilometrage' => 45000,
                'abs' => true,
                'image1_path' => 'storage/voitures/voiture.png',
                'image2_path' => 'storage/voitures/voiture2.png',
                'image3_path' => 'storage/voitures/voiture.png',
                'image4_path' => 'storage/voitures/voiture2.png',
                'jantes' => '17',
                'sellerie' => 'Tissus',
                'couleur' => '#000000',
                'type' => 'BERLINE',
                'cylindree' => '1.8l',
                'prix' => 25000.00,
                'description' => 'Audi A3 en excellent état, bien entretenue avec carnet complet.',
            ],
            [
                'user_id' => 1,
                'brand_id' => 1, // Audi
                'fuel_id' => 2, // Diesel
                'model' => 'Q5',
                'etat' => 'neuf',
                'annee' => 2023,
                'kilometrage' => 0,
                'abs' => true,
                'image1_path' => 'storage/voitures/voiture.png',
                'image2_path' => 'storage/voitures/voiture2.png',
                'image3_path' => 'storage/voitures/voiture.png',
                'image4_path' => 'storage/voitures/voiture2.png',
                'jantes' => '19',
                'sellerie' => 'Cuir',
                'couleur' => '#1E90FF',
                'type' => 'SUV',
                'cylindree' => '2l',
                'prix' => 55000.00,
                'description' => 'SUV familial Audi Q5 avec options haut de gamme.',
            ],
            [
                'user_id' => 1,
                'brand_id' => 2, // BMW
                'fuel_id' => 1, // Essence
                'model' => 'Série 3',
                'etat' => 'occasion',
                'annee' => 2019,
                'kilometrage' => 60000,
                'abs' => true,
                'image1_path' => 'storage/voitures/voiture.png',
                'image2_path' => 'storage/voitures/voiture2.png',
                'image3_path' => 'storage/voitures/voiture.png',
                'image4_path' => 'storage/voitures/voiture2.png',
                'jantes' => '18',
                'sellerie' => 'Cuir',
                'couleur' => '#FFFFFF',
                'type' => 'BERLINE',
                'cylindree' => '2l',
                'prix' => 32000.00,
                'description' => 'BMW Série 3 très bien entretenue, finition luxe.',
            ],
            [
                'user_id' => 1,
                'brand_id' => 2, // BMW
                'fuel_id' => 3, // Electrique
                'model' => 'iX3',
                'etat' => 'neuf',
                'annee' => 2023,
                'kilometrage' => 0,
                'abs' => true,
                'image1_path' => 'storage/voitures/voiture.png',
                'image2_path' => 'storage/voitures/voiture2.png',
                'image3_path' => 'storage/voitures/voiture.png',
                'image4_path' => 'storage/voitures/voiture2.png',
                'jantes' => '19',
                'sellerie' => 'Cuir',
                'couleur' => '#FF0000',
                'type' => 'SUV',
                'cylindree' => 'NONE',
                'prix' => 65000.00,
                'description' => 'BMW iX3 100% électrique, autonomie 450km.',
            ],
            [
                'user_id' => 1,
                'brand_id' => 3, // Mercedes
                'fuel_id' => 1, // Essence
                'model' => 'Classe C',
                'etat' => 'occasion',
                'annee' => 2018,
                'kilometrage' => 75000,
                'abs' => true,
                'image1_path' => 'storage/voitures/voiture.png',
                'image2_path' => 'storage/voitures/voiture2.png',
                'image3_path' => 'storage/voitures/voiture.png',
                'image4_path' => 'storage/voitures/voiture2.png',
                'jantes' => '17',
                'sellerie' => 'Tissus',
                'couleur' => '#808080',
                'type' => 'BERLINE',
                'cylindree' => '1.8l',
                'prix' => 28000.00,
                'description' => 'Mercedes Classe C élégante, intérieur spacieux.',
            ],
            [
                'user_id' => 1,
                'brand_id' => 3, // Mercedes
                'fuel_id' => 2, // Diesel
                'model' => 'GLC',
                'etat' => 'neuf',
                'annee' => 2022,
                'kilometrage' => 0,
                'abs' => true,
                'image1_path' => 'storage/voitures/voiture.png',
                'image2_path' => 'storage/voitures/voiture2.png',
                'image3_path' => 'storage/voitures/voiture.png',
                'image4_path' => 'storage/voitures/voiture2.png',
                'jantes' => '19',
                'sellerie' => 'Cuir',
                'couleur' => '#000080',
                'type' => 'SUV',
                'cylindree' => '2l',
                'prix' => 60000.00,
                'description' => 'Mercedes GLC diesel, parfait pour longs trajets.',
            ],
            [
                'user_id' => 1,
                'brand_id' => 4, // Porsche
                'fuel_id' => 1,
                'model' => '911 Carrera',
                'etat' => 'occasion',
                'annee' => 2019,
                'kilometrage' => 35000,
                'abs' => true,
                'image1_path' => 'storage/voitures/voiture.png',
                'image2_path' => 'storage/voitures/voiture2.png',
                'image3_path' => 'storage/voitures/voiture.png',
                'image4_path' => 'storage/voitures/voiture2.png',
                'jantes' => '19',
                'sellerie' => 'Cuir',
                'couleur' => '#FFD700',
                'type' => 'BERLINE',
                'cylindree' => '3l',
                'prix' => 110000.00,
                'description' => 'Porsche 911 Carrera, sportive mythique.',
            ],
            [
                'user_id' => 1,
                'brand_id' => 4, 
                'fuel_id' => 3, // Electrique
                'model' => 'Taycan',
                'etat' => 'neuf',
                'annee' => 2023,
                'kilometrage' => 0,
                'abs' => true,
                'image1_path' => 'storage/voitures/voiture.png',
                'image2_path' => 'storage/voitures/voiture2.png',
                'image3_path' => 'storage/voitures/voiture.png',
                'image4_path' => 'storage/voitures/voiture2.png',
                'jantes' => '19',
                'sellerie' => 'Cuir',
                'couleur' => '#00FF00',
                'type' => 'BERLINE',
                'cylindree' => 'NONE',
                'prix' => 120000.00,
                'description' => 'Porsche Taycan 100% électrique, 700ch.',
            ],
            [
                'user_id' => 1,
                'brand_id' => 5, 
                'fuel_id' => 3, 
                'model' => 'Model 3',
                'etat' => 'occasion',
                'annee' => 2021,
                'kilometrage' => 15000,
                'abs' => true,
                'image1_path' => 'storage/voitures/voiture.png',
                'image2_path' => 'storage/voitures/voiture2.png',
                'image3_path' => 'storage/voitures/voiture.png',
                'image4_path' => 'storage/voitures/voiture2.png',
                'jantes' => '18',
                'sellerie' => 'Cuir',
                'couleur' => '#C0C0C0',
                'type' => 'BERLINE',
                'cylindree' => 'NONE',
                'prix' => 48000.00,
                'description' => 'Tesla Model 3, grande autonomie, autopilot.',
            ],
            [
                'user_id' => 1,
                'brand_id' => 5,
                'fuel_id' => 3,
                'model' => 'Model X',
                'etat' => 'neuf',
                'annee' => 2023,
                'kilometrage' => 0,
                'abs' => true,
                'image1_path' => 'storage/voitures/voiture.png',
                'image2_path' => 'storage/voitures/voiture2.png',
                'image3_path' => 'storage/voitures/voiture.png',
                'image4_path' => 'storage/voitures/voiture2.png',
                'jantes' => '19',
                'sellerie' => 'Cuir',
                'couleur' => '#FFFFFF',
                'type' => 'SUV',
                'cylindree' => 'NONE',
                'prix' => 95000.00,
                'description' => 'Tesla Model X avec portes Falcon et 7 places.',
            ],
            
        ]);
    }
}
